name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Test - Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - "3.3.1"
        rails:
          - "7.1"
          - "8.0"
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    runs-on: ubuntu-latest
    steps:
      - name: Set BUNDLE_GEMFILE
        run: echo "BUNDLE_GEMFILE=gemfiles/rails_${RAILS_VERSION//./_}.gemfile" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec on Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}
        run: bundle exec rake spec
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rake rubocop
